#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "joal"
name = "Joal"
description.en = "An open source command line RatioMaster with an optional WebUI."

version = "1.0~ynh1"

maintainers = ["christophehenry"]

[upstream]
license = "Apache-2.0"
website = "https://github.com/anthonyraymond/joal"
admindoc = "https://github.com/anthonyraymond/joal/blob/master/README.md"
code = "https://github.com/anthonyraymond/joal"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/joal"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    default = ""

[resources]
    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/anthonyraymond/joal/releases/download/2.1.36/joal.tar.gz"
    sha256 = "b4fcb6b2f74a7753ef236d15097ab3bd059771a325627164bca5e92f37194218"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    
    websocket.url = "/websocket/"
    websocket.auth_header = false
    websocket.show_tile = false
    websocket.protected= true
    websocket.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "default-jre"