#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================
unslashed_path=$(echo "$path" | sed 's/\///g')

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$data_dir"
find "$data_dir" -type f -name "*.jar" -exec mv '{}' "$install_dir/joal.jar" \;
chown -R "$app:$app" "$data_dir"
chown -R "$app:www-data" "$install_dir"
# Allow other torrents apps to move .torrent here
chmod 777 "$data_dir/torrents"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx
ynh_config_add_systemd
yunohost service add "$app" --description="An open source command line RatioMaster with an optional WebUI." --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
